openapi: 3.0.0
info:
  description: This is the market place's products service. This service handles any
    actions related to products
  version: 1.0.0
  title: Market Place
  contact:
    name: Vanderson Assis
    email: assis.vanderson@gmail.com
paths:
  /products:
    post:
      tags:
        - Products
      summary: Creates a new product
      description: The product passed will be saved in the database
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        description: Product object that will be added to our database
        required: true
      responses:
        "200":
          description: Products response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Invalid data object
        "405":
          description: Validation exception
    put:
      tags:
        - Products
      summary: Updates an existing product
      description: The product will be updated in the database
      operationId: updateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        description: Product object that will be updated in our database
        required: true
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
        "405":
          description: Validation exception
  "/products/{idProduct}":
    delete:
      tags:
        - Products
      summary: Deletes a product document
      description: The product that contains the parameter id will be deleted
      operationId: deleteProduct
      parameters:
        - in: path
          name: idProduct
          required: true
          description: Id of the product to be deleted
          schema:
            type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found
        "405":
          description: Validation exception
  "/products/{idSeller}/seller":
    get:
      tags:
        - Products
      summary: List all the products in our market place for the selected seller
      description: This endpoint will return all the products we have registered in our
        database
      operationId: listProductsBySeller
      parameters:
        - in: path
          name: idSeller
          required: true
          description: The seller's id to return its products
          schema:
            type: string
      responses:
        "200":
          description: Products response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductListResponse"
        "401":
          description: Authorization failed
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  "/products/lock":
    post:
      tags:
        - Products
      summary: Locks the quantity of products sent in the payload
      description: If enough products for the quantity in the payload, they will be locked, so the order can go on. If the order fails, the locked products will be
                   unlocked to be sold to another customer.
      operationId: lockProductQuantity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductLock"
        description: The product lock object containing the product id and quantity to be locked.
        required: true
      responses:
        "200":
          description: The product's quantity has been locked and can be safely ordered.
        "400":
          description: This status code will be returned if the quantity passed is greater then the available or
            if the request is malformed. Either way, there will be a descriptive message and internal code to why the error
            happened.
        "401":
          description: The client is not authorized to access this endpoint
        "500":
          description: Something went wrong in the server side. The client can't do anything about it and should report the error to the system administrator.
servers:
  - url: http://localhost/market-place/api/v1
components:
  schemas:
    Product:
      type: object
      required:
        - idSeller
        - name
        - model
        - description
        - price
        - quantity
      properties:
        id:
          type: string
        idSeller:
          type: string
        name:
          type: string
        model:
          type: string
        description:
          type: string
        price:
          type: number
          minimum: 0.01
        quantity:
          type: integer
          format: int32
    ProductListResponse:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    ProductLock:
      type: object
      required:
        - idProduct
        - quantity
      properties:
        idProduct:
          type: string
        quantity:
          type: integer
          format: int32